

services:

  db:
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - app-network
    volumes:
      - data_base_data:/var/lib/posgresql/data
  

  app:
    build: .
    ports:
      - "8080:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  data_base_data: